language: node_js
node_js:
- 6.11.0
- 8.1.1
script:
- npm test
after_success:
- cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
- bash <(curl -s https://codecov.io/bash)
- rm -rf ./coverage
deploy:
  provider: npm
  email: lonly197@qq.com
  api_key:
    secure: aG/fiTjg+ajROPs5tKwGtrNTkPHwqyZsWo+UY1Qh28Vw698jEdWzMKY6rGZhufKfLrbbss7syZwfZJy8rBT0qhab/HZ2vsqWXMK/+iUI6tzhzkqTQdPVPIxJHQ6iwxPucsPv1oH1YeXQfScsv0ip//1psMODXg6Lf0xk0gwRSjOZ+hIS5gzzh3+SpOfaxufsi8V0nNoyaENN9CmT/oEhS02rAWqEK3c/LnKiGAupcsbk21D65I93BqBaOEVt8fGhhJ8m2W6XdDeqi2usOU7+8/N1xbkowKSL/qW6iPT9s0NuDEvnnAxQsBgyU+ilIqscVpDJUso4XKx38gRn9aYK0OnFpXfenkUWj8RztyFkdAWeg/ymEOykTSo9j0eG5V4+a2/jqsdPF0omWwNQdY8nUHGT0E8Voo1QEZ5NhnbBcsi2Mt14b/fdwP4nPUkAxu1s3lWe0rKFMu4D/ZNEFtF/qAUlkxHMiU1T3gG6IrbzOhbTVGdXJpmJ99zmr/+I4DM4sWOPu0nszxY+Ej59c2NsG4WpcT9CaUX4qwsOFobiqscXxxM53BCMxjNnxl2Xj0+czpwfshoPLyzOWUYyZdKtJ6JdxiyhFWgy40Fm1m8/X0VKxnsyIrRGD4alfds9yOtrlpTfDAVZJsf5E3npEwFPMdwbyiHqelQiqn6I+QASkDM=
  on:
    tags: true
    repo: lonly197/uuidjs
